
(defun inspiration ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/663377/"
  (interactive)
  (color-theme-install
   '(inspiration
     ((background-color . "#0d1112")
      (foreground-color . "#9cb0b8")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#657b83")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))
     (hl-line ((t (:background "#151515"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))     
     (font-lock-comment-face ((t (:foreground "#4c2d3c"))))
     (font-lock-constant-face ((t (:foreground "#851878"))))
     (font-lock-builtin-face ((t (:foreground "#00B2BD"))))
     (font-lock-function-name-face ((t (:foreground "#0492FF"))))
     (font-lock-variable-name-face ((t (:foreground "#b58900"))))
     (font-lock-keyword-face ((t (:foreground "#0055FF"))))
     (font-lock-string-face ((t (:foreground "#F53326"))))
     (font-lock-doc-string-face ((t (:foreground "#F53326"))))
     (font-lock-type-face ((t (:foreground "#27EC95"))))
     )))

(provide 'inspiration)
