(defun justin-color-theme ()
  (interactive)
  (color-theme-install
   '(justin-color-theme
      ((background-color . "#4b5e63")
      (background-mode . dark)
      (border-color . "#86858a")
      (cursor-color . "#b09b9b")
      (foreground-color . "#545031")
      (mouse-color . "black"))
     (fringe ((t (:background "#86858a"))))
     (mode-line ((t (:foreground "#ffffff" :background "#84848b"))))
     (hl-line ((t (:background "#98a0b7"))))     
     (region ((t (:background "#b0b0b0"))))
     (font-lock-builtin-face ((t (:foreground "#8b5e27"))))
     ;; (font-lock-comment-face ((t (:foreground "#7d827d"))))
     (font-lock-comment-face ((t (:foreground "#4c2da3"))))
     (font-lock-function-name-face ((t (:foreground "#f21c53"))))
     (font-lock-keyword-face ((t (:foreground "#3b1adb"))))
     (font-lock-string-face ((t (:foreground "#b66216"))))
     (font-lock-type-face ((t (:foreground"#199915"))))
     (font-lock-variable-name-face ((t (:foreground "#e69941"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'justin-color-theme)
